export const privacyPage = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Privacy · Equidistant</title>
<style>body{margin:0;background:#edf1ed;color:#172019;font:16px/1.65 system-ui,sans-serif}main{max-width:740px;margin:auto;padding:36px 24px 64px}h1{font:600 36px Georgia,serif}h2{font-size:21px;margin-top:30px}a{color:#087f73}li{margin:10px 0}</style></head>
<body><main><a href="/">← Equidistant</a><h1>Privacy at Equidistant</h1><p>Updated 9 September 2026</p>
<p>Equidistant helps groups choose a meeting place in London. For privacy questions or requests about data held by the app, contact Ben Jones at <a href="mailto:btjones.me@gmail.com">btjones.me@gmail.com</a>.</p>
<h2>Your Google account</h2><p>Sign-in provides your Google account identifier, verified email address and, when available, name. We use these to identify your account, manage sessions, enforce recommendation limits and grant access to approved features. We do not request access to your Gmail, contacts, calendar or files.</p>
<p>A secure, HTTP-only cookie keeps you signed in for up to seven days. The server stores a hash of its random session token, along with your account details. Signing out revokes that session. Short-lived sign-in records expire after ten minutes; expired records are removed during routine sign-in cleanup.</p>
<h2>Your group and map</h2><p>Normal travel-time planning runs in your browser using a downloaded model. Participant names, starting locations and map settings are saved in this browser, separately for each Google account. They are not synchronized between devices. Clearing this site's browser data removes these saved workspaces. Signing out preserves them for your next visit.</p>
<h2>Services used when you search</h2><ul>
<li>Address searches send the search text to OpenStreetMap's Nominatim service.</li>
<li>Venue recommendations send the meeting-area coordinates and your search text to Google Places and OpenAI, including web research. Avoid putting private personal information in a venue search. Recommendation requests to OpenAI use its no-response-storage setting; providers' own processing and retention rules still apply.</li>
<li>Approved live travel-time comparisons send starting and destination coordinates through our server to TravelTime. These comparisons are optional and restricted to approved accounts.</li>
<li>Map tiles and venue photos are loaded from map and place providers. Their services receive the network information needed to deliver that content.</li>
</ul>
<p>Recommendations are cached on the server for up to 24 hours, separately for each account. Search timestamps enforce a rolling one-hour limit; older quota records are removed during later requests. Aggregate cost counters are retained for approximately 40 days. Expired cache records are removed during routine cache cleanup.</p>
<h2>Usage and hosting</h2><p>A separate anonymous browser cookie lasts up to one year. Sign-ins update aggregate browser counts and coarse country, region and city information supplied by the hosting service. The app does not store raw IP addresses in these records; sign-in abuse controls use hashed client addresses. Google Analytics is configured with advertising and analytics cookie storage denied, but can receive cookieless usage measurements. Hosting and other providers also process network information and operational logs under their own policies.</p>
<p>Account information and recommendation caches are stored in the app's server database. Participant workspaces remain in browser storage. We do not include Google email addresses or names in analytics events.</p>
<h2>Your choices</h2><p>You can sign out from the app menu, clear this site's browser data, and remove Equidistant from your Google account's connected apps. To request removal of server-held account information or ask about its use, contact the address above.</p>
</main></body></html>`;
