name: Python Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.8  # we should read this from pyproject.toml

      - name: Install dependencies
        run: |
          sudo snap install dotnet-sdk --classic
          sudo snap alias dotnet-sdk.dotnet dotnet
          sudo add-apt-repository -y ppa:ubuntugis/ppa
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libreadline-gplv2-dev libncursesw5-dev libssl-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
          sudo apt-get install -y --no-install-recommends libffi-dev
          sudo apt-get install -y --no-install-recommends lzma liblzma-dev
          sudo apt-get install -y --no-install-recommends libgeos-dev libgeos++-dev
          sudo apt-get install -y --no-install-recommends libproj-dev proj-data proj-bin
          sudo apt-get install -y --no-install-recommends libsnappy-dev
          sudo apt-get install -y --no-install-recommends python3-h5py
          sudo apt-get install -y --no-install-recommends gdal-bin libgdal-dev python3-gdal
          python -m pip install --upgrade pip poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest .
